-- MySQL Script generated by MySQL Workbench
-- Fri Aug  2 18:09:17 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema best_project
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema best_project
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `best_project` DEFAULT CHARACTER SET utf8 ;
USE `best_project` ;

-- -----------------------------------------------------
-- Table `best_project`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `best_project`.`User` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `User_name` VARCHAR(45) NOT NULL,
  `User_surname` VARCHAR(45) NOT NULL,
  `User_pseudo` VARCHAR(45) NOT NULL,
  `User_password` VARCHAR(20) NOT NULL,
  `User_email` VARCHAR(20) NULL,
  `User_phone` VARCHAR(20) NULL,
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `best_project`.`Location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `best_project`.`Location` (
  `idLocation` INT NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `adress` VARCHAR(45) NOT NULL,
  `idUser` INT NOT NULL,
  PRIMARY KEY (`idLocation`, `idUser`),
  INDEX `idUser_idx` (`idUser` ASC) VISIBLE,
  CONSTRAINT `idUser`
    FOREIGN KEY (`idUser`)
    REFERENCES `best_project`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `best_project`.`Cours`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `best_project`.`Cours` (
  `idCours` INT NOT NULL AUTO_INCREMENT,
  `IndiceCours` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`idCours`),
  INDEX () VISIBLE,
  UNIQUE INDEX `idCours_UNIQUE` (`idCours` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `best_project`.`Offre de cours`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `best_project`.`Offre de cours` (
  `idOffre_de_cours` INT GENERATED ALWAYS AS (),
  `idUser` INT NOT NULL,
  `idCours` INT NOT NULL,
  PRIMARY KEY (`idOffre_de_cours`, `idUser`, `idCours`),
  INDEX `idUser_idx` (`idUser` ASC) VISIBLE,
  INDEX `idCours_idx` (`idCours` ASC) VISIBLE,
  CONSTRAINT `idUser`
    FOREIGN KEY (`idUser`)
    REFERENCES `best_project`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idCours`
    FOREIGN KEY (`idCours`)
    REFERENCES `best_project`.`Cours` (`idCours`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `best_project`.`Demande de cours`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `best_project`.`Demande de cours` (
  `idDemande_de_cours` INT GENERATED ALWAYS AS (),
  `idUser` INT NOT NULL,
  `idCours` INT NOT NULL,
  PRIMARY KEY (`idDemande_de_cours`, `idUser`, `idCours`),
  INDEX `idUser_idx` (`idUser` ASC) VISIBLE,
  INDEX `idCours_idx` (`idCours` ASC) VISIBLE,
  CONSTRAINT `idUser`
    FOREIGN KEY (`idUser`)
    REFERENCES `best_project`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idCours`
    FOREIGN KEY (`idCours`)
    REFERENCES `best_project`.`Cours` (`idCours`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `best_project` ;

-- -----------------------------------------------------
-- Placeholder table for view `best_project`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `best_project`.`view1` (`id` INT);

-- -----------------------------------------------------
-- View `best_project`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `best_project`.`view1`;
USE `best_project`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
